### ISSUE TITLE
Не прекращайте поддержку.

### ISSUE THREAD

**Issue by Morgomirius** [trofimchuk-t/AIMP.NET-Remote-API#1]
Пожалуйста, не прекращайте поддержку данного API. На шарпе и так по импу ничего хорошего нет, а я как-раз делаю адекватный remote control для uwp без танцев с бубном через rpc-json. И, кстати 
 Marshal.PtrToStringAuto((IntPtr)AInfo.ToInt64() во всех экземплярах замените ToInt32 на ToInt64, так как переполнение разряда происходит на новых версиях аимпа.

**Comment by ByteAntGitHub** [comment]
Ок. И спасибо за замечание, поправлю.

**Comment by trofimchuk-t** [comment]
Ок, спасибо, поправлю в ближайшем времени.
