### ISSUE TITLE
Events and aimp.Position

### ISSUE THREAD

**Issue by botiapa** [trofimchuk-t/AIMP.NET-Remote-API#3]
The events are not working for me. Here is how I use them:

```
aimp = new AimpRemote();
aimp.TrackStarted += Aimp_TrackStarted;
aimp.TrackInfoChanged += Aimp_TrackInfoChanged;

var timer = new Timer();
timer.Interval = 1000;
timer.Elapsed += Timer_Tick;
timer.Start();
```

And also, how can I use the aimp.position property? Because every time I set it to something is just goes back to the start of the song. Example

```
aimp.Position = new TimeSpan(0, 1, 30);
Console.WriteLine(aimp.Position);
```

And it writes 0:0:0.

**Comment by trofimchuk-t** [comment]
Hi!
I have fixed a bug with setting of the AIMP position, now it should works.

Regarding events: looks like that events doesn't working if we use api wrapper in the console applications.
Could you try it within WinForms app?
